import Head from 'next/head'
import Image from "next/image";
import Promo from "../image/Promo002.png"

export default function Home() {
    return (
        <div>
            <Head>
                <title>AniList</title>
                <meta name="description" content="Generated by create next app "/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="relative">
                <div className="mt-12 flex justify-evenly px-5">
                    <div className="mt-40 tb:mt-0">
                        <div className="text-5xl font-bold">A new level of <br/> anime listings</div>
                        <div className="text-xl mt-6 max-w-lg ">
                            What are your highest rated genres or most watched voice actors?
                            Follow your watching habits over time with in-depth statistics.
                        </div>
                        <button className="mt-8 mb-20 font-extrabold py-2 px-4 bg-regal-red rounded-3xl w-60">Join now
                        </button>
                    </div>
                    <div className="max-w-[450px] tb:hidden">
                        <Image src={Promo}/>
                    </div>
                </div>
                <div className="border-b-[10vh] border-b-solid border-b-regal-red max-w-xs
                border-l-[100vw] border-l-solid border-l-transparent bottom-full absolute
                bottom-0 "/>
            </div>
            <div className="bg-regal-red min-h-[300px]">

            </div>
        </div>
    )
}
