import Head from 'next/head'
import Link from "next/link";
import React from "react";

export default function Login() {
    return (
        <div>
            <Head>
                <title>Log In</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div
                className="bg-regal-gray text-center font-roboto max-w-[400px] tb:max-w-full tb:min-h-screen p-[40px] mt-[60px] mx-auto tb:m-0">
                <div className="mb-[60px] mt-[20px] font-semibold text-2xl">Login</div>
                <div className="flex flex-col max-w-[320px] tb:max-w-full mx-auto mt-[60px]">
                    <input placeholder="Email"
                           className="mb-6 outline-none h-10 bg-white-gray rounded text-regal-gray px-4 text-white"
                           type="text"/>
                    <input placeholder="Password"
                           className="mb-6 outline-none h-10 bg-white-gray rounded text-regal-gray px-4 text-white"
                           type="password"/>
                    <div className=" mx-auto bg-regal-red py-[6px] w-[110px] font-semibold rounded-sm cursor-pointer">
                        Login
                    </div>
                    <div className="text-sm mt-6 text-blue-gray cursor-pointer">Forgot password?</div>
                    <div className="text-sm mt-20 text-blue-gray">
                        Not registered? <Link href="/signup"><a className="text-regal-red">Create a new
                        account</a></Link>
                    </div>
                </div>
            </div>
        </div>
    )
}
