import Head from 'next/head'
import React from 'react';
import Link from "next/link";

export default function Signup() {
    return (
        <div>
            <Head>
                <title>Sign Up</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div
                className="bg-regal-gray text-center font-roboto max-w-[400px] tb:max-w-full tb:min-h-screen p-[40px] mt-[60px] mx-auto tb:m-0">
                <div className="mb-[60px] mt-[20px] font-semibold text-2xl">Sign up to AniList</div>
                <div className="flex flex-col max-w-[320px] tb:max-w-full mx-auto mt-[60px]">
                    <input placeholder="Email"
                           className="mb-6 outline-none h-10 bg-white-gray rounded text-regal-gray px-4 text-white"
                           type="text"/>
                    <input placeholder="Username"
                           className="mb-6 outline-none h-10 bg-white-gray rounded text-regal-gray px-4 text-white"
                           type="text"/>
                    <input placeholder="Password"
                           className="mb-6 outline-none h-10 bg-white-gray rounded text-regal-gray px-4 text-white"
                           type="password"/>
                    <input placeholder="Confirm Password"
                           className="mb-6 outline-none h-10 bg-white-gray rounded text-regal-gray px-4 text-white"
                           type="password"/>
                    <div className="text-sm text-blue-gray">
                        You agree to our terms of service
                    </div>
                    <div className="mt-9 mx-auto bg-regal-red py-[6px] w-[110px] font-semibold rounded-sm cursor-pointer">
                        Sign-up
                    </div>
                    <div className="text-sm mt-20 text-blue-gray">
                        <Link href="/login"><a>Login</a></Link> • <Link href="/verify"><a>Resend Verification Email</a></Link>
                    </div>
                </div>
            </div>
        </div>
    )
}
