import Head from 'next/head'

export default function Social() {
    return (
        <div>
            <Head>
                <title>Social</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="text-3xl underline">Social</div>
        </div>
    )
}
